export const countryCodes = [
    { code: '+1', iso: 'us' },
    { code: '+7', iso: 'ru' },
    { code: '+20', iso: 'eg' },
    { code: '+27', iso: 'za' },
    { code: '+30', iso: 'gr' },
    { code: '+31', iso: 'nl' },
    { code: '+32', iso: 'be' },
    { code: '+33', iso: 'fr' },
    { code: '+34', iso: 'es' },
    { code: '+36', iso: 'hu' },
    { code: '+39', iso: 'it' },
    { code: '+40', iso: 'ro' },
    { code: '+41', iso: 'ch' },
    { code: '+43', iso: 'at' },
    { code: '+44', iso: 'gb' },
    { code: '+45', iso: 'dk' },
    { code: '+46', iso: 'se' },
    { code: '+47', iso: 'no' },
    { code: '+48', iso: 'pl' },
    { code: '+49', iso: 'de' },
    { code: '+51', iso: 'pe' },
    { code: '+52', iso: 'mx' },
    { code: '+53', iso: 'cu' },
    { code: '+54', iso: 'ar' },
    { code: '+55', iso: 'br' },
    { code: '+56', iso: 'cl' },
    { code: '+57', iso: 'co' },
    { code: '+58', iso: 've' },
    { code: '+60', iso: 'my' },
    { code: '+61', iso: 'au' },
    { code: '+62', iso: 'id' },
    { code: '+63', iso: 'ph' },
    { code: '+64', iso: 'nz' },
    { code: '+65', iso: 'sg' },
    { code: '+66', iso: 'th' },
    { code: '+81', iso: 'jp' },
    { code: '+82', iso: 'kr' },
    { code: '+84', iso: 'vn' },
    { code: '+86', iso: 'cn' },
    { code: '+90', iso: 'tr' },
    { code: '+91', iso: 'in' },
    { code: '+92', iso: 'pk' },
    { code: '+93', iso: 'af' },
    { code: '+94', iso: 'lk' },
    { code: '+95', iso: 'mm' },
    { code: '+98', iso: 'ir' },
    { code: '+212', iso: 'ma' },
    { code: '+213', iso: 'dz' },
    { code: '+216', iso: 'tn' },
    { code: '+218', iso: 'ly' },
    { code: '+220', iso: 'gm' },
    { code: '+221', iso: 'sn' },
    { code: '+222', iso: 'mr' },
    { code: '+223', iso: 'ml' },
    { code: '+224', iso: 'gn' },
    { code: '+225', iso: 'ci' },
    { code: '+226', iso: 'bf' },
    { code: '+227', iso: 'ne' },
    { code: '+228', iso: 'tg' },
    { code: '+229', iso: 'bj' },
    { code: '+230', iso: 'mu' },
    { code: '+231', iso: 'lr' },
    { code: '+232', iso: 'sl' },
    { code: '+233', iso: 'gh' },
    { code: '+234', iso: 'ng' },
    { code: '+235', iso: 'td' },
    { code: '+236', iso: 'cf' },
    { code: '+237', iso: 'cm' },
    { code: '+238', iso: 'cv' },
    { code: '+239', iso: 'st' },
    { code: '+240', iso: 'gq' },
    { code: '+241', iso: 'ga' },
    { code: '+242', iso: 'cg' },
    { code: '+243', iso: 'cd' },
    { code: '+244', iso: 'ao' },
    { code: '+245', iso: 'gw' },
    { code: '+246', iso: 'io' },
    { code: '+248', iso: 'sc' },
    { code: '+249', iso: 'sd' },
    { code: '+250', iso: 'rw' },
    { code: '+251', iso: 'et' },
    { code: '+252', iso: 'so' },
    { code: '+253', iso: 'dj' },
    { code: '+254', iso: 'ke' },
    { code: '+255', iso: 'tz' },
    { code: '+256', iso: 'ug' },
    { code: '+257', iso: 'bi' },
    { code: '+258', iso: 'mz' },
    { code: '+260', iso: 'zm' },
    { code: '+261', iso: 'mg' },
    { code: '+262', iso: 're' },
    { code: '+263', iso: 'zw' },
    { code: '+264', iso: 'na' },
    { code: '+265', iso: 'mw' },
    { code: '+266', iso: 'ls' },
    { code: '+267', iso: 'bw' },
    { code: '+268', iso: 'sz' },
    { code: '+269', iso: 'km' },
    { code: '+290', iso: 'sh' },
    { code: '+291', iso: 'er' },
    { code: '+297', iso: 'aw' },
    { code: '+298', iso: 'fo' },
    { code: '+299', iso: 'gl' },
    { code: '+350', iso: 'gi' },
    { code: '+351', iso: 'pt' },
    { code: '+352', iso: 'lu' },
    { code: '+353', iso: 'ie' },
    { code: '+354', iso: 'is' },
    { code: '+355', iso: 'al' },
    { code: '+356', iso: 'mt' },
    { code: '+357', iso: 'cy' },
    { code: '+358', iso: 'fi' },
    { code: '+359', iso: 'bg' },
    { code: '+370', iso: 'lt' },
    { code: '+371', iso: 'lv' },
    { code: '+372', iso: 'ee' },
    { code: '+373', iso: 'md' },
    { code: '+374', iso: 'am' },
    { code: '+375', iso: 'by' },
    { code: '+376', iso: 'ad' },
    { code: '+377', iso: 'mc' },
    { code: '+378', iso: 'sm' },
    { code: '+380', iso: 'ua' },
    { code: '+381', iso: 'rs' },
    { code: '+382', iso: 'me' },
    { code: '+383', iso: 'xk' },
    { code: '+385', iso: 'hr' },
    { code: '+386', iso: 'si' },
    { code: '+387', iso: 'ba' },
    { code: '+389', iso: 'mk' },
    { code: '+420', iso: 'cz' },
    { code: '+421', iso: 'sk' },
    { code: '+423', iso: 'li' },
    { code: '+500', iso: 'fk' },
    { code: '+501', iso: 'bz' },
    { code: '+502', iso: 'gt' },
    { code: '+503', iso: 'sv' },
    { code: '+504', iso: 'hn' },
    { code: '+505', iso: 'ni' },
    { code: '+506', iso: 'cr' },
    { code: '+507', iso: 'pa' },
    { code: '+508', iso: 'pm' },
    { code: '+509', iso: 'ht' },
    { code: '+590', iso: 'gp' },
    { code: '+591', iso: 'bo' },
    { code: '+592', iso: 'gy' },
    { code: '+593', iso: 'ec' },
    { code: '+594', iso: 'gf' },
    { code: '+595', iso: 'py' },
    { code: '+596', iso: 'mq' },
    { code: '+597', iso: 'sr' },
    { code: '+598', iso: 'uy' },
    { code: '+599', iso: 'cw' },
    { code: '+670', iso: 'tl' },
    { code: '+672', iso: 'nf' },
    { code: '+673', iso: 'bn' },
    { code: '+674', iso: 'nr' },
    { code: '+675', iso: 'pg' },
    { code: '+676', iso: 'to' },
    { code: '+677', iso: 'sb' },
    { code: '+678', iso: 'vu' },
    { code: '+679', iso: 'fj' },
    { code: '+680', iso: 'pw' },
    { code: '+681', iso: 'wf' },
    { code: '+682', iso: 'ck' },
    { code: '+683', iso: 'nu' },
    { code: '+685', iso: 'ws' },
    { code: '+686', iso: 'ki' },
    { code: '+687', iso: 'nc' },
    { code: '+688', iso: 'tv' },
    { code: '+689', iso: 'pf' },
    { code: '+690', iso: 'tk' },
    { code: '+691', iso: 'fm' },
    { code: '+692', iso: 'mh' },
    { code: '+850', iso: 'kp' },
    { code: '+852', iso: 'hk' },
    { code: '+853', iso: 'mo' },
    { code: '+855', iso: 'kh' },
    { code: '+856', iso: 'la' },
    { code: '+880', iso: 'bd' },
    { code: '+886', iso: 'tw' },
    { code: '+960', iso: 'mv' },
    { code: '+961', iso: 'lb' },
    { code: '+962', iso: 'jo' },
    { code: '+963', iso: 'sy' },
    { code: '+964', iso: 'iq' },
    { code: '+965', iso: 'kw' },
    { code: '+966', iso: 'sa' },
    { code: '+967', iso: 'ye' },
    { code: '+968', iso: 'om' },
    { code: '+970', iso: 'ps' },
    { code: '+971', iso: 'ae' },
    { code: '+972', iso: 'il' },
    { code: '+973', iso: 'bh' },
    { code: '+974', iso: 'qa' },
    { code: '+975', iso: 'bt' },
    { code: '+976', iso: 'mn' },
    { code: '+977', iso: 'np' },
    { code: '+992', iso: 'tj' },
    { code: '+993', iso: 'tm' },
    { code: '+994', iso: 'az' },
    { code: '+995', iso: 'ge' },
    { code: '+996', iso: 'kg' },
    { code: '+998', iso: 'uz' }
];

export const getPhoneMaxLength = (code: string): number => {
    switch (code) {
        case '+1': return 10;
        case '+44': return 10;
        case '+353': return 9;
        case '+61': return 9;
        case '+91': return 10;
        case '+92': return 10;
        case '+971': return 9;
        case '+966': return 9;
        case '+351': return 9;
        case '+64': return 9;
        case '+27': return 9;
        case '+49': return 11;
        case '+33': return 9;
        case '+39': return 10;
        case '+34': return 9;
        case '+81': return 10;
        case '+86': return 11;
        case '+55': return 11;
        case '+52': return 10;
        default: return 15;
    }
};
